name: E2E Tests
run-name: E2E Tests
on:
  # Only allow manual triggers
  workflow_dispatch:
  pull_request: # TODO: remove
#  push:
#    branches:
#      - jakule/playwright-assist

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: build
          path: ${{ github.workspace }}/build/

      - name: Build Images
        run: |
          make -C e2e build
      - name: Run Tests
        run: |
          make -C e2e test