name: E2E Tests
run-name: E2E Tests
on:
  # Only allow manual triggers
  workflow_dispatch:
  pull_request: # TODO: remove

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./e2e/docker-compose.yml"
#          down-flags: "--volumes"
#          services: |
#            helloworld2
#            helloworld3